version: '3.8'

services:
  postgres:
    image: db
    build:
      context: .
      dockerfile: Dockerfile.postgre
      target: db
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog-app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: my-adminer-container
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-express-container
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/blog-app
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  pgdata:
